### parser pour un fichier

In [3]:
import camelot
tables = camelot.read_pdf("/Users/AI/Mes Documents/VS code/projet LLM/Docugami/KG-RAG-datasets/nih-clinical-trial-protocols/data/v1/docs/NCT06151600_Prot_000.pdf", pages="all", flavor="lattice")
dfs = [t.df for t in tables]

In [4]:
dfs[0]

,0,1
0,Title,AProspectiveNaturalHistoryandOutcomeMeasure\nD...
1,StudySponsor,ElpidaTherapeuticsSPC\n12643RanchoBernardoRd\n...
2,SponsorContact,TerryPirovolakis\nCEO&Founder\nPh:(416)625-193...
3,LeadPrincipalInvestigator,"SusanT.Iannaccone,MD\nProfessor,PediatricNeuro..."
4,ProtocolVersionandDate,Version1(6-July2023)

In [5]:
dfs[5]

,0,1,2,3
0,,,magneticspine\ngrowingrods)or\nshrapnelfragmen...,
1,Neuropsychologicaland\nPhysicaltherapy\nAssess...,Aseriesofperformance-\nbasedactivitiestoassess...,Discomfortor\npsychologicalstress\nandtiredness.,Subjects\nallowedtotake\nbreaks.
2,PulmonaryFunction\nTests(PFTs),PFTstoidentifyseverity\nandprogressionof\npulm...,Noknownrisks.May\nfeeltiredafterthe\nprocedure.,Subjects\nallowedtotake\nbreaks.
3,ScoliosisseriesX-ray,ScoliosisseriesX-ray\nincludesthethoracic\nspi...,Exposuretominimal\namountofradiation.,Adherenceto\ntheminimum\nexposureto\nradiation...
4,Bloodcollection,Exploratoryblooddraw,Minorpainand\nbruising,Adherenceto\nmaximumblood\nvolumes\npermittedin

In [7]:
dfs[0].head

<bound method NDFrame.head of                            0  \
0                      Title
1               StudySponsor
2             SponsorContact
3  LeadPrincipalInvestigator
4     ProtocolVersionandDate

                                                   1
0  AProspectiveNaturalHistoryandOutcomeMeasure\nD...
1  ElpidaTherapeuticsSPC\n12643RanchoBernardoRd\n...
2  TerryPirovolakis\nCEO&Founder\nPh:(416)625-193...
3  SusanT.Iannaccone,MD\nProfessor,PediatricNeuro...
4                               Version1(6-July2023)  >

In [8]:
import pdfplumber

with pdfplumber.open("/Users/AI/Mes Documents/VS code/projet LLM/Docugami/KG-RAG-datasets/nih-clinical-trial-protocols/data/v1/docs/NCT06151600_Prot_000.pdf") as pdf:
    for p in pdf.pages:
        for t in p.extract_tables():
            for r in t:
                print(r)

['Title ', 'A  Prospective  Natural  History  and  Outcome  Measure \nDiscovery  Study  of  Charcot-Marie-Tooth  Disease,  Type  4J ']
['Study  Sponsor ', 'Elpida  Therapeutics  SPC \n12643  Rancho  Bernardo  Rd \nSan  Diego,  CA  92127 ']
['Sponsor  Contact ', 'Terry  Pirovolakis \nCEO  &  Founder \nPh:  (416)  625-1933;  terry@elpidatx.com ']
['Lead  Principal  Investigator ', 'Susan  T.  Iannaccone,  MD \nProfessor,  Pediatric  Neurology,  University  of  Texas \nSouthwestern  Medical  Center \nPh:  (214)  456-5220;  susan.iannaccone@utsouthwestern.edu ']
['Protocol  Version  and  Date ', 'Version  1  (6-July2023) ']
['Study  Title ', 'A  Prospective  Natural  History  and  Outcome  Measure  Discovery  Study  of \nCharcot-Marie-Tooth  Disease,  Type  4J ']
['Sponsor ', 'Elpida  Therapeutics  SPC ']
['Trial  Phase ', 'Observational ']
['Study  Population ', 'Subjects  with  a  genetically  confirmed  diagnosis  of  CMT4J  will  be  included. ']
['Investigational  Site ', '4  US  sites \n•  University of Texas Southwestern Medical Center /Children’s Health \n•  University  of  Iowa \n•  NIH  (National  Institute  of  Neurological  Disorders  and  Stroke) \n•  Stanford  School  of  Medicine ']
['Study  Objectives \n\n', '•  To  gain  a  better  understanding  of  the  course  of  illness \n•  To  collect  data  about  genotype-phenotype  correlations  to  allow  for  better \nprediction  of  disease  progression  based  on  genetic  information \n•  To  investigate  and  follow  at  long  term  different  outcome  measurements \n(e.g.,  motor,  quality  of  life,  radiologic  and  electrophysiological) \n•  To  expedite  research  and  access  to  new  therapies  for  rare  conditions  like \nCMT4J ']
['Study  Design ', 'A  multicenter,  longitudinal,  prospective  observational  natural  history  study  of \nsubjects  with  a  molecular  confirmed  diagnosis  of  CMT4J ']
['Eligibility  Criteria ', 'Inclusion  Criteria: \n1.  Male  or  female,  all  ages \n2.  A  molecularly-confirmed  diagnosis  of  CMT4J  (confirmed  by  a  CLIA \ncertified,  CE-marked,  or  equivalent  lab):  Genomic  DNA  mutation \nanalysis  demonstrating  1)  bi-allelic  pathogenic  and/or  likely \npathogenic  variants  (by  ACMG  criteria)  in  the  FIG4  gene,  or  2)  bi-\nallelic  variants  with  one  pathogenic  and/or  likely  pathogenic  variant \nin  trans  with  a  variant  of  uncertain  significance  if  laboratory  evidence \nand  expert  consensus  exits  in  support  of  loss  of  FIG4  function  exists. \n3.  Informed  consent  from  patients  18  years  or  older  who  are  able  to \nprovide  consent  and  from  caregivers;  parent(s)/guardian(s)  providing \nconsent  for  subjects  younger  than  18  years  at  Screening  and  patients \nolder  than  18  years  unable  to  provide  informed  consent \n4.  Informed  assent  of  patients  younger  than  18  years  at  Screening  who \nare  able  to  provide  assent \n5.  Able  and  willing  to  comply  with  the  study  protocol,  including  travel \nto  Study  Center,  procedures,  measurements  and  visits \n\nExclusion  Criteria:  \n1.  Any  known  genetic  abnormality,  including  chromosomal  aberrations \nthat  confound  the  clinical  phenotype  \n2.  Current  participation  in  an  interventional  or  therapeutic  study  \n3.  Receiving  an  investigational  drug  within  90  days  of  the  Baseline  Visit ']
['1.  Any  known  genetic  abnormality,  including  chromosomal  aberrations ']
['that  confound  the  clinical  phenotype  ']
['', '4.  Prior  or  current  treatment  with  gene  or  stem  cell  therapy \n5.  Any  other  diseases  which  may  significantly  interfere  with  the \nassessment  of  CMT4J \n6.  Have  any  other  conditions,  which,  in  the  opinion  of  the  Investigator \nor  Sponsor  would  make  the  subject  unsuitable  for  inclusion  or  could \ninterfere  with  the  subject  participating  in  or  completing  the  study ']
['Study  Duration ', 'Subject  visits  will  occur  every  12  months  +  4  weeks  for  up  to  2  years  for  the \ninitial  period  with  extension  of  up  to  60  months  if  feasible.  No  investigational \nproduct  will  be  used  during  the  study. ']
['Assessments ', 'Clinical  Assessments: \n•  Electrophysiology \n•  Nerve  Conduction  Studies  (NCS)  \n•  Pulmonary  Function  Tests  (PFTs) \n•  Scoliosis  series  X-ray \n•  Magnetic  Resonance  Imaging  \n1.  Thigh  and  calf  muscle  without  contrast \n2.  Brain  without  contrast \n\nNeuropsychological  Assessments: \n•  Vineland  Adaptive  Behavior  Score,  3rd  edition \n•  Bayley  Scales  of  Infant  and  Toddler  Development-III \n•  Wechsler  Abbreviated  Scale  of  Intelligence  Second  Edition  /  Wechsler \nPreschool  &  Primary  Scale  of  Intelligence  Fourth  Edition  (WASI-II  / \nWPPSI-IV) \n•  Stanford-Binet  V  (SB5) \n\nPhysical  Therapy  Assessments: \n•  PEDICAT \n•  CMTPedS  for  subjects  5  to  17  years  of  age \n•  CMTInfS  (<  4  years  old) \n•  CMTNSv2  for  subjects  >18  years  of  age \n•  CMT-FOM  for  subjects  >  18  years  of  age \n•  Timed  Up  and  Go  Test  (TUG)  \n\nQuestionnaires:  \n•  PedsQL  (2-18  years) \n•  ONLS  (18  years  and  older) \n•  pCMT-QOL  PRO  (8-18  years)  \n•  pCMT-QOL  parent  proxy  (8-18  years) \n•  pCMT-QOL  parent  proxy  (0-7  years) \n•  CMT  Health  Index  (CMTHI)  for  >18  years  of  age \n']
['', 'Exploratory  Assessments: \n•  Blood  collection  for  exploratory  biomarker \n•  Wearable  devices \n•  Optional  skin  biopsy ']
['STATISTICAL \nCONSIDERATIONS ', 'The  sample  size  of  20  subjects  is  expected  to  provide  sufficient  insights  into \nthe  natural  history  of  individuals  with  CMT4J,  a  rare  disease,  to  provide \nexploratory  and  descriptive  results  and  guide  the  design  of  future  studies  of \nCMT4J.  No  formal  sample  size  estimation  was  performed  for  this  study. \nParametric  and  non-parametric  tests  will  be  used  to  analyze  possible \nassociations  between  clinical,  radiographic,  and  laboratory  data.  The  tests  will \nbe  selected  based  on  the  question  being  asked  of  the  database.  This  database \nwill  be  used  to  analyze  multiple  medical  issues  among  subjects  with  confirmed \nCMT4J. ']
['1.  Any  known  genetic  abnormality,  including  chromosomal  aberrations  that  confound  the ']
['clinical  phenotype  ']
[None, 'equires  20  min  to']
['administer  and  is  a  reliable  and  sensitive  15-item  functional  outcome  measure  for  early  onset  CMT  and', None]
['related  neuropathies.  The  CMTInfS  can  be  implemented  in  natural  history  studies  to  understand  the', None]
['rate  of  progression  at  the  earliest  stages  of  disease  in  preparation  for  therapeutic  trials  of  early', None]
['interventions.', None]
['Procedures  and  Risks ', 'Description ', 'Risk ', '', 'Mitigation ', '']
[None, None, None, None, 'measures ', None]
['Neurology  Clinic  Visit ', 'Vital  signs, \nanthropometrics,  history \nof  present  illness  and \ninterim  information  will \nbe  obtained. \nPhysical  examination \nincluding  general, \nneurological  exam \n(including  MMT)  and \nhand-held  dynamometry ', 'Discomfort  or \npsychological  stress.  ', 'Subjects \nallowed  to  take \nbreaks. ', None, None]
['CMT  Specific  Scales \n-  CMTPedS  for \nsubjects  5-17 \nyears  of  age \n-  CMTInfS  <  4 \nyears  of  age \n-  CMTNSv2  for \nsubjects  >18 \nyears  of  age \n-  CMT-FOM  for \nsubjects  >  18 \nyears  of  age \n-  CMT  Health \nIndex  (CMTHI) \nfor  >18  years  of \nage ', 'Validated  clinical \noutcome  measures  to \nmonitor  progression  of \nsensorimotor  function, \ndisease-burden  and \nquality  of  life  in  CMT \nsubjects  ', 'No  known  risks.  \nMay  experience  mild \nfrustration  or  fatigue \nwith  challenging  tasks.  \nMay  experience  mild \npsychological \ndiscomfort  when \ncompleting  rating \nforms  on  topics \nincluding  school \nperformance,  mood, \nand  quality  of  life. ', 'Subjects \nallowed  to  take \nbreaks. ', None, None]
['Electrophysiology \nNerve  Conduction \nStudies  (NCS) ', 'Evaluates  sensory  and \nmotor  responses  in  the \nupper  and  lower \nextremities  including \ndistal  latency,  amplitude \nand  conduction  velocity. ', 'Risk  of  discomfort \nwith  muscle \ncontraction  from \nstimulation.  \nMild  muscle  soreness \nand  fatigue.  \nDiscomfort  from \nstaying  still  during  the \nprocedure. ', 'Procedure \nexpectations \nwill  be \ncommunicated \nwith  the \nsubjects  and \ntime  will  be \ngiven  between \nstimulations. ', None, None]
['Magnetic  Resonance \nImaging  of  the  thigh  and \ncalf  muscle  without \ncontrast \n\n\n\nBrain  MRI  without \ncontrast ', 'MRI  scan  of  the  thigh  and \ncalf  muscle  to \ncharacterize  the  structural \nabnormalities  in  CMT4J. \n\n\n\nMRI  scan  of  the  brain. ', 'Risk  for  injury  from \nthe  MRI  magnet  if \npresent:  pacemakers  or \nother  implanted \nelectrical  devices, \nbrain  stimulators,  some \ndental  implants, \naneurysm  clips, \nmetallic  prostheses, \npermanent  eyeliners, \nimplanted  delivery \npump,  magnetic \ndevices  (such  as ', 'Individuals  are \nscreened  to \nensure  MRI \nsafety \nprocedures  are \nmet  before  a \nscan \nHearing \nprotection  for \nrisk  of  hearing \ndamage ', None, None]
['', '', 'magnetic  spine \ngrowing  rods)  or \nshrapnel  fragments.  \nRisk  of  discomfort \nfrom  laying  on  hard \nsurface  or  anxiety  if \nfear  of  confined  spaces \nor  loud  noises \n', '']
['Neuropsychological  and \nPhysical  therapy \nAssessments ', 'A  series  of  performance-\nbased  activities  to  assess \npsychomotor  functioning \nand  quality  of  life.  This \nincludes: \n•  Vineland \nAdaptive \nBehavioral  Scale \n•  PEDICAT \n•  PedsQL \n•  ONLS \n•  pCMT-QOL \n•  Bayley-III,  \n•  WASI-II, \nWPPSI-IV \n•  Stanford-Binet \ntest  V \n•  TUG ', 'Discomfort  or \npsychological  stress \nand  tiredness.  ', 'Subjects \nallowed  to  take \nbreaks. ']
['Pulmonary  Function \nTests  (PFTs) ', 'PFTs  to  identify  severity \nand  progression  of \npulmonary  dysfunction. \nLung  volume \nmeasurements:  Forced \nVital  Capacity-FVC, \nForced  Expiratory \nVolume-FEV,  and  Forced \nExpiratory  Flow-FEF. \nPressure  Measurements: \nmaximal  inspiratory  and \nexpiratory. ', 'No  known  risks.  May \nfeel  tired  after  the \nprocedure. ', 'Subjects \nallowed  to  take \nbreaks. \n']
['Scoliosis  series  X-ray ', 'Scoliosis  series  X-ray \nincludes  the  thoracic \nspine  (upper  back)  and \nthe  lumbar  spine  (lower \nback)  to  identify  areas  of \nspine  curvature. ', 'Exposure  to  minimal \namount  of  radiation. ', 'Adherence  to \nthe  minimum \nexposure  to \nradiation  as \npermittable. ']
['Blood  collection ', 'Exploratory  blood  draw ', 'Minor  pain  and \nbruising ', 'Adherence  to \nmaximum  blood \nvolumes \npermitted  in ']
['Bayley-III,']
['WASI-II,']
['WPPSI-IV']
['', '', '', 'pediatric \nsubjects ']
['Skin  biopsy  (optional) ', 'Small  punch  biopsy  for \nfuture  exploratory  use ', 'Exposure  to  lidocaine \ncream  and  a  small \nirritation  to  the  skin  for \nthe  punch  biopsy ', 'Only  trained \nindividuals  can \nperform  a  skin \nbiopsy ']
['Descriptor ', 'Definition  (guidelines) ']
['UNRELATED  CATEGORY ', None]
['Unrelated ', 'The  AE  is  clearly  not  related  to  the  study  or  to  disease  progression. \nThe  AE  is  completely  related  to  an  etiology  other  than  the  study \nprocedures  (the  alternative  etiology  must  be  documented  in  the \nstudy subject’s medical record) or disease progression. ']
['Unlikely ', 'The  AE  is  doubtfully  related  to  the  study  or  to  disease  progression \nand  likely  to  be  related  to  factors  other  than  study  procedures. ']
['RELATED  CATEGORIES ', None]
['Possible ', 'The  AE  may  be  related  to  a  study  procedure  or  to  disease \nprogression.  There  is  an  association  between  the  event  and  the \nstudy  procedures  and  there  is  a  plausible  mechanism  for  the  event \nto  be  related  to  the  study  procedures;  there  may  be  also  an \nalternative etiology, such as characteristics of the subject’s clinical\nstatus  and/or  underlying  disease. ']
['Probable ', 'The  AE  is  likely  related  to  a  study  procedure  or  to  disease \nprogression.  There  is  (1)  an  association  between  the  event  and  the \nstudy  procedures,  (2)  a  plausible  mechanism  for  the  event  to  be \nrelated  to  the  study  procedures,  and  (3)  the  event  could  not  be \nreasonably explained by known characteristics of the subject’s\nclinical  status  and/or  an  alternative  etiology  is  not  apparent. ']
['Definite ', 'The  AE  is  clearly  related  to  a  study  procedure  or  to  disease \nprogression.  There  is  (1)  an  association  between  the  event  and  the \nstudy  procedures,  (2)  a  plausible  mechanism  for  the  event  to  be \nrelated  to  the  related  to  the  study  procedure,  and  (3)  causes  other \nthan  the  study  procedures  have  been  ruled  out  and/or  the  event  re-\nappeared  on  re-exposure  to  the  study  procedure. ']
['', 'Study  Day', '', '', 'Screening ', '', '', 'Baseline ', '', '', 'Month  12 ', '', '', 'Month  24 ', '']
['', '  n  o  ', '', '', '', '', '', '(        ) ', '', '', '(        ) ', '', '', '(        ) ', '']
['Informed  Consent ', None, None, 'X ', None, None, '', None, None, '', None, None, '', None, None]
['Medical  Information ', None, None, '', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None]
['', 'Demographics ', '', '', '', '', '', '', '', '', '', '', '', '', '']
['Medical  History ', None, None, '', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None]
['Family  History ', None, None, '', None, None, 'X ', None, None, '', None, None, '', None, None]
['CMT4J  Diagnosis  and  History  ', None, None, '', None, None, 'X ', None, None, '', None, None, '', None, None]
['', 'Clinical  Procedures ', '', '', '', '', '', '', '', '', '', '', '', '', '']
['Inclusion/Exclusion  Criteria ', None, None, 'X ', None, None, '', None, None, '', None, None, '', None, None]
['Vital  Signsa ', None, None, '', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None]
['Height  and  Weight ', None, None, '', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None]
['Physical  Examb ', None, None, '', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None]
['Neurological  Examc ', None, None, '', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None]
['Urine  Pregnancy  (for  female \nsubjects)d ', None, None, '', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None]
['Blood  Collection  for  Future \nExploratory  Analysise ', None, None, '\n', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None]
['Skin  biopsy  (optional,  any  visit, \nonly  once) ', None, None, '', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None]
['', 'Adverse  Events ', '', '', '', '', '', 'X ', '', '', 'X ', '', '', 'X ', '']
['Concomitant  Medications ', None, None, '', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None]
['', 'CMT  Scales* ', '', '', '', '', '', None, None, '', None, None, '', None, None]
['CMTPedSf ', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None]
['CMTInfSg ', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None]
['CMTNSv2h ', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None]
['CMT-FOMh ', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None]
['CMT  Health  Index  (CMTHI)h ', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None]
['', 'Clinical  Studies ', '', '', '', '', '', '', '', '', '', '', '', '', '']
['Thigh  and  Calf  MRI  without \ncontrast ', None, None, '', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None]
['Brain  MRI  without  contrast ', None, None, '', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None]
['Nerve  Conduction  Study  (NCS)i ', None, None, '', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None]
['Pulmonary  Function  Test  (PFT)j ', None, None, '', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None]
['Scoliosis  Series  X-rayk ', None, None, '', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None]
['', 'Neuropsychological  and  Physical ', '', '', None, None, '', None, None, '', None, None, '', None, None]
[None, 'Therapy  Assessments ', None, None, None, None, None, None, None, None, None, None, None, None, None]
['Vineland  Adaptive  Behavior  Scale ', None, None, '', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None]
['PEDICATl ', None, None, '', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None]
['Bailey  III ', None, None, '', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None]
['WASI-II  or  WPPSI-IV ', None, None, '', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None]
['Stanford  Binet  –  V ', None, None, '', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None]
['Timed  up  and  go  (TUG) ', None, None, '', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None]
['Wearable  devices ', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None]
['', 'Questionnaires ', '', '', '', '', '', '', '', '', '', '', '', '', '']
['PedsQLm ', None, None, '', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None]
['Overall  Neuropathy  Limitation \nScale  (ONLS)  (18  years  and  older) ', None, None, '', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None]
['pCMT-QOL  PRO  (8  to  18  years) ', None, None, '', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None]
['pCMT-QOL  (8  to  18  years  parent-\nproxy) ', None, None, '', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None]
['pCMT-QOL  (0  to  7  years  parent-\nproxy) ', None, None, '', None, None, 'X ', None, None, 'X ', None, None, 'X ', None, None]

In [14]:
import pdfplumber

with pdfplumber.open("/Users/AI/Mes Documents/VS code/projet LLM/Docugami/KG-RAG-datasets/nih-clinical-trial-protocols/data/v1/docs/NCT06151600_Prot_000.pdf") as pdf:
    for p in pdf.pages:
        for t in p.extract_tables():
            for r in t:
                if r == t[0][0]:
                    print(r)

In [19]:
with pdfplumber.open("/Users/AI/Mes Documents/VS code/projet LLM/Docugami/KG-RAG-datasets/nih-clinical-trial-protocols/data/v1/docs/NCT06151600_Prot_000.pdf") as pdf:
    first_table = pdf.pages[0].extract_tables()[0]

    print(first_table[0][1])

A  Prospective  Natural  History  and  Outcome  Measure
Discovery  Study  of  Charcot-Marie-Tooth  Disease,  Type  4J

In [20]:
import os
import pdfplumber

folder = "/Users/AI/Mes Documents/VS code/projet LLM/Docugami/KG-RAG-datasets/nih-clinical-trial-protocols/data/v1/docs"

for filename in os.listdir(folder):
    if filename.lower().endswith(".pdf"):
        pdf_path = os.path.join(folder, filename)
        print(f"\n=== {filename} ===")

        with pdfplumber.open(pdf_path) as pdf:
            for page in pdf.pages:
                tables = page.extract_tables()
                if not tables:
                    continue

                for table in tables:
                    for row in table:
                        print(row)

=== NCT06157684_Prot_000.pdf ===
['All participants will be assigned a study ID when they are enrolled. Throughout the study, this ID will be']
['used to link their de-identified study data to the study key which will include PHI and identifiable data']
['that are collected on the data form. The remainder of the data which will by associated with the study ID']
['will be collected in REDCap. The study key will be kept in a secure file in a password protected folder on']
['the hospital network drive. The key will be destroyed upon completion of the manuscript.']

=== NCT06150378_Prot_SAP_000.pdf ===
['', 'pre-infiltration\n(24-48hours\nprior)', '', '1month\npost-infiltration', '', '3months\npost-infiltration', '', '6months\npost-infiltration']
['Evaluator', 'Principal\ninvestigator', '', 'ShoulderFellow', '', 'ShoulderFellow\n(clinicalvariables)\nSonographer(imaging\nvariables)', '', 'ShoulderFellow\n(clinicalvariables)']
['Variables\nClinics', '-Demographic\n-Mobility\n-Pain\n-Functional\nScores(ASES–\nConstant-\nPittsburgh)', '', '-Mobility\n-Pain\n-Functional\nScores(ASES–\nConstant-Pittsbu\nrgh)\n-complications', '', '-Mobility\n-Pain\n-FunctionalScores\n(ASES–\nConstant-Pittsburgh)\n-complications', '', '-Mobility\n-Pain\n-FunctionalScores\n(ASES–\nConstant-Pittsburg\nh)\n-complications']
['Imaging\nvariables', 'Magnetic\nnuclear\nresonance\nEcodoppler\nmusculoesquel\nético', '', '', '', 'Ecodoppler\nmusculoesquelético', '', '']

=== NCT06152900_Prot_SAP_000.pdf ===
['TERM', 'DEFINITION', 'TERM', 'DEFINITION']
['AE', 'Adverse Event', 'ICH E6', 'International Conference on\nHarmonization Guidance for Industry,\nGood Clinical Practice: Consolidated\nGuidance']
['ADE', 'Adverse Device Effect', 'ICMJE', 'International Committee of Medical\nJournal Editors']
['ANCOVA', 'Analysis of Covariance', 'IDE', 'Investigational Device Exemption']
['BMI', 'Body Mass Index', 'IFU', 'Instructions for Use']
['CFR', 'Code of Federal Regulations', 'ISO', 'International Organization for\nStandardization']
['CGAIS', 'Clinician Global Aesthetic Improvement\nScale', 'IRB', 'Institutional Review Board']
['CIP', 'Clinical Investigation Plan', 'MOP', 'Manual of Procedures']
['CMP', 'Clinical Monitoring Plan', 'NRS', 'Numeric Rating Scale for pain assessment']
['CRF', 'Case Report Form', 'OHRP', 'Office for Human Research Protections']
['CRO', 'Contract Research Organization', 'PI', 'Principal Investigator']
['CV', 'Curriculum Vitae', 'PSQ', 'Patient Satisfaction Questionnaire']
['DCC', 'Data Coordination Center', 'QA', 'Quality Assurance']
['DSMB', 'Data Safety Monitoring Board', 'QC', 'Quality Control']
['EC', 'Ethics Committee', 'RF', 'Radiofrequency']
['eCRF', 'Electronic Case Report Form', 'Rhytidectomy', 'Mini facelift']
['ETE', 'Expected Treatment Effect', 'SAE', 'Serious Adverse Event']
['FDA', 'Food and Drug Administration', 'SAP', 'Statistical Analysis Plan']
['FDAAA', 'Food and Drug Administration\nAmendments Act of 2007', 'SADE', 'Serious Adverse Device Effect']
['GAIS', 'Global Aesthetic Improvement Scale', 'SGAIS', 'Subject Global Aesthetic Improvement\nScale']
['GCP', 'Good Clinical Practice', 'SMC', 'Safety Monitoring Committee']
['GLP', 'Good Laboratory Practice', 'SOP', 'Standard Operating Procedure']
['GMP', 'Good Manufacturing Practice', 'UADE', 'Unanticipated Adverse Device Effect']
['HIPAA', 'Health Information Portability and\nAccountability Act', 'USA', 'United States of America']
['IB', 'Investigator’s Brochure', '', '']
['ICH', 'International Committee on\nHarmonization', '', '']
['Protocol Number:', 'AFL19006']
['Protocol Title:', 'Prospective Clinical Evaluation of the Safety and Efficacy of NON-INVASIVE Electronic Stimulation\nfor Improvement of Muscle Strength and Toning, Circumferential Reduction of the Core and\nExtremities']
['Investigational Devices:', 'The Accufit Electrical Muscle Stimulation device is an FDA cleared two-channel muscle\nstimulator that provides up to 8 electrodes with unique waveforms for muscle stimulation.']
['Development Phase:', 'Evaluation']
['Study Objective:', 'The objective of this clinical study is to assess the safety and efficacy of a novel electrical\nstimulation device for use in improving muscle strength and toning of the core and extremities.']
['Brief Study Overview:', 'Open-label, baseline-controlled, multi-center study evaluating an electrical muscle stimulation\nsystem for Improvement of Muscle Strength and Toning, Circumferential Reduction of the Core\nand Extremities The study will enroll up to 60 subjects desiring and to improve muscle strength\nand tone and circumferential reduction in their core and extremities. Each subject will receive\nup to 8 bi-weekly treatments over a 4-week period. Follow up visits planned for 30- and 90-days\npost treatment. Measurement outcomes will be compared to baseline.']
['Number of Sites\nEnrolling Participants:', 'Up to 6 sites']
['Sample Size:', 'The study will enroll up to 60 male and female subjects ≥ 18 years to 60 years of age who are\nseeking to improve muscle strength and tone in the extremities.']
['Subject Population:', 'Healthy, female and male adult subjects age 18 to 60 years who meet the inclusion/exclusion\ncriteria.']
['Inclusion Criteria:', '1. Able to read, understand and voluntarily provide written informed consent.\n2. Healthy male or female, ≥ 18 years to 65 years of age seeking treatment for improved\nmuscle strength and muscle toning in their core and extremities.\n3. Subject is determined to be physically fit and agrees to not making any major changes\nin their diet or lifestyle during the study.\n4. Able and willing to comply with the treatment/follow-up schedule and requirements.\n5. Women of child-bearing age are required to be using a reliable method of birth control\nat least 3 months prior to study enrollment and for the duration of the study as well as\nhave a negative Urine Pregnancy test at baseline.']
['Exclusion Criteria:', '1. Pregnant in the last 3 months, intending to become pregnant, postpartum or nursing in\nthe last 6 months.\n2. Any previous liposuction/lipo-sculpture or any type of surgical procedure in the\ntreatment area in the past 12 months.\n3. History of immunosuppression/immune deficiency disorders (including AIDS and HIV\ninfection) or use of immunosuppressive medications, 6 months prior to and during the\nstudy.\n4. History of hyperlipidemia, diabetes mellitus, hepatitis, blood coagulopathy or excessive\nbleeding.\n5. Having a history of skin cancer or any other cancer in the areas to be treated, including\npresence of malignant or premalignant pigmented lesions.\n6. Having a permanent implant in the treatment area such as metal plates or an injected\nchemical substance such as silicone in the treatment area.\n7. Suffering from significant skin conditions in the treatment area or inflammatory skin\nconditions including but not limited to open lacerations, abrasions, herpes sores, cold\nsores, active infections.\n8. Poor skin quality (severe laxity).\n9. Abdominal wall, muscular abnormality or hernia on physical examination.\n10. As per the investigator’s discretion, any physical or mental condition which may make it\nunsafe for the subject to participate.']
['', '11. Subjects unwilling or unable to adhere to all study requirements for treatment and\nfollow-up.\n12. Investigator may exclude any subject at any time at his/her discretion.']
['Primary Endpoint:', 'Photographic evaluation by an independent, blinded reviewer with correct identification of pre-\ntreatment baseline images when compared to post-treatment images taken at follow up visits.']
['Secondary Endpoints:', '1. Global Aesthetic Improvement grading by Expert Clinician.\n2. Improvement of muscle strength as measured by a dynamometer at follow up visits\ncompared to baseline measurements.\n3. Reduction in core circumference as measured by Seca Circumferential System at follow\nup visits compared to baseline measurement.\n4. To assess subject satisfaction using Satisfaction Survey at each follow up visit.']
['Safety Endpoints:', 'Subject’s assessment of discomfort as measured by a 0-10 numeric rating scale.\nSubjects experiencing a treatment-related adverse event (AE).']
['Study Duration:', 'The duration from when the study opens to enrollment for 12 months.']
['Participant Duration:', '7 months']
['Function']
['Sponsor']
['Clinical Research Director']
['Frequency', 'Up to 4khz']
['Output power', 'Up to a 100mA']
['Number of Electrodes', '8 electrodes with disposables contact pads']
['Simulation', 'Biphasic and Interferential Waveforms']
['Pulse Repetition Rate', 'Up to 200Hz']
['Pulse Width', 'Up to 290 us']
['Handpieces/Delivery System', 'Single use Hydrogel electrode Round or Square']
['', '', '', '', '', '', '', '', '', '', 'FU 30', 'FU 90']
['', 'Screening', 'Tx 1', 'Tx 2', 'Tx 3', 'Tx 4', 'Tx 5', 'Tx 6', 'Tx 7', 'Tx 8', 'day', 'days']
['Informed\nConsent', 'x', '', '', '', '', '', '', '', '', '', '']
['Pregnancy\nVerification', 'x', '', '', '', '', '', '', '', '', '', '']
['Concomitant\nMedications', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x']
['Medical History', 'x', '', '', '', '', '', '', '', '', '', '']
['Demographics', 'x', '', '', '', '', '', '', '', '', '', '']
['Weight', 'x', '', '', '', '', '', '', '', '', 'x', 'x']
['Dynamometer\nMeasurements', 'x', '', '', '', '', '', '', '', '', 'x', 'x']
['Circumferential\nMeasurements', 'x', '', '', '', '', '', '', '', '', 'x', 'x']
['Photography\n(pre- and - post\ntreatment)', '', 'x', '', '', '', '', '', '', '', 'x', 'x']
['Subject\nSatisfaction', '', '', '', '', '', '', '', '', '', 'x', 'x']
['Pain Scale Rating', '', '', 'x', 'x', 'x', 'x', 'x', 'x', 'x', '', '']
['Adverse Events', '', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x']
['Definite', 'Definite relationship exists between the device/procedure and an adverse\nevent']
['Probably Related', 'A reasonable causal relationship between the device/procedure and an\nadverse event is more likely than not.']
['Possibly Related', 'A reasonable relationship exists between the device/procedure and an adverse\nevent, but the causal relationship is unclear or lacking.']
['Not Likely Related', 'A temporal relationship exists between the device/procedure and an adverse\nevent, but there is no reasonable causal relationship. For example, the adverse\nevent occurs in a time frame, which makes a causal relationship to device\ntreatment improbable.']
['Unrelated', 'No relationship between treatment with the device/procedure and the\nadverse event exists.']
['VERSION', 'DATE', 'SIGNIFICANT REVISIONS']
['V1.0', '6/25/2020', 'Initial Release']
['V2.0', '9/8/2021', 'Expand to include extremities, strength measurements, investigators']
['', '', '']
['', '', '']
['', '', '']
['', '', '']
['', '', '']
['', '', '']
['', '', '']
['', '', '']
['', '', '']
['', '', '']

=== NCT06156735_Prot_SAP_000.pdf ===

=== NCT06152679_Prot_000.pdf ===
['Dr Bethany Treadgold,', 'Research Fellow & Qualitative Advisor', '', None]
['Primary Care Research Group & NIHR Research Design Service, South West', None, None, '']
['Title of Study', 'Understanding the patient experience of day-case bladder tumour\nresection, and prostate resection or enucleation: Qualitative patient\ninterviews.']
['Protocol Number', '3 (16/10/23)']
['Sponsor R&D No:', 'TBC']
['Number of Study Sites', '6+']
['Number of participants', '15, with plans to expand in increments of 3 until thematic saturation is\nreached']
['Study Design', 'Semi-structured qualitative interviews']
['Participant population', 'Patients who have recently undergone day-case transurethral resection\nof bladder tumour, transurethral resection of prostate, or transurethral\nenucleation of the prostate.']
['Aim', 'To understand patient experiences following day-case transurethral\nresection of bladder tumour (TURBT), transurethral resection of\nprostate (TURP), and transurethral enucleation of prostate (TUEP).']
['Main Criteria for\nInclusion', 'Inclusion Criteria:\n● Adults aged >18 who have recently undergone day-case TURBT or\nTURP or TUEP\n● Able and willing to provide informed consent\nExclusion Criteria:\n● Patients who had surgery that was not performed as a day-case']
['Study Duration', '18 Months']
['Study Period', 'April 2023 – October 2024']
['Study Summary', 'A qualitative research study interviewing patients treated in hospitals\nacross England. We will interview patients who have recently undergone\none of the following operations as a day-case; transurethral bladder\ntumour resection (TURBT), transurethral resection of prostate (TURP) or\ntransurethral enucleation of the prostate (TUEP). We are interested to\nfind out about the experience for patients who go home on the day of\nsurgery after they have had one of these operations. We hope that the\nfindings will tell us about how to improve the experience for patients in\nfuture.\nPatients undergoing day-case surgery at a range of different hospitals\nfrom across England with varying day-case rates will be interviewed.\nHospitals in large city and more rural areas will be included. Interviews\nare anticipated to take place over a six month period between December\n2023 and May 2024. The study will end when “saturation” is achieved,\nwhereby no new themes are identified through interviews. Saturation']
['', 'will be sought for each individual operation of interest. Analysis and write\nup will take place from May 2024 – October 2024.']
['Amendment\nNumber', 'Revised Protocol\nVersion Number\nand date', 'Details of key changes made (including\njustification if required)']
['Amendment 1', 'Version 1\n(15.11.22) revised\nbased on\nfeedback to\nproduce version 2\n(17.02.23)', 'Changes based on PPIE meeting 14.02.2023\n-  Remove assumptions around recovery in\nown home being preferable in PLS.\n-  Wording modifications to questions for\nclarity.\n-  Have telephone interviews as an available\noption as well as video conferencing.\n-  Specify that study is within NHS hospitals.\n-  Question about information provided for\npatients.\nBased on supervision from qualitative\nresearcher\n- Increase introductory questions.\n- re-frame questions in more open format.\n- reduce overall number of questions in\norder to achieve “semi-structured”\ninterview aim.']
['Amendment 2', '', '']
['an ISO:9001 (quality) and ISO: 27001 (information security) and Cyber Essentials certified']
['business. I attach a document describing their data security and management.']
['TIME POINT', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11 (6\nMONTHS)']
['Hospital\nidentification', 'X', '', '', '', '', '', '', '', '', '', '']
['Consent clinical\nleads', '', 'X', '', '', '', '', '', '', '', '', '']
['Candidate\ninterviewee\nidentification', '', 'X', '', '', '', '', '', '', '', '', '']
['Interviewee\nexpression of\ninterest', '', '', 'X', '', '', '', '', '', '', '', '']
['Inclusion/Exclusion', '', '', '', 'X', '', '', '', '', '', '', '']
['Consent', '', '', '', '', 'X', '', '', '', '', '', '']
['Interview', '', '', '', '', '', 'X', '', '', '', '', '']
['Demographic data', '', '', '', '', '', 'X', '', '', '', '', '']
['Transcription', '', '', '', '', '', '', 'X', '', '', '', '']
['Interim thematic\nanalysis', '', '', '', '', '', '', '', 'X', '', '', '']
['Study conclusion\n(when thematic\nsaturation is\nreached)', '', '', '', '', '', '', '', '', 'X', '', '']
['Analysis', '', '', '', '', '', '', '', '', '', 'X', '']
['Dissemination', '', '', '', '', '', '', '', '', '', '', 'X']
['Milestones', '0 –2m', '3–4m', '4–6m', '6–10m']
['Ethical/Governance approvals', '', '', '', '']
['Recruitment', '', '', '', '']
['Data collection', '', '', '', '']
['Data analysis', '', '', '', '']
['Write-up', '', '', '', '']

=== NCT06159946_Prot_000.pdf ===

=== NCT06152367_Prot_000.pdf ===
['System', 'GRADE 3', 'GRADE 4', 'ALL EVENTS']
['General', '', '', '']
['Chills', '70 (13%)', '0 (0%)', '271 (52%)']
['Fever', '29 (6%)', '5 (1%)', '154 (29%)']
['Malaise Infection', '43 (8%)', '0 (0%)', '143 (27%)']
['', '29 (6.0%)', '7 (1%)', '66 (13%)']
['Cardiovascular System', '', '', '']
['Hypotension', '205 (39%)', '15 (3%)', '375 (71%)']
['Cardiovascular Disorders', '36 (7)', '7 (1%)', '59 (11%)']
['Digestive System', '', '', '']
['Diarrhea', '113 (22%)', '10 (2%)', '350 (67%)']
['Vomiting', '111 (21%)', '7 (1%)', '261 (50%)']
['Nausea', '25 (5%)', '0 (0%)', '186 (35%)']
['Nausea and Vomiting', '25 (5%)', '2 (0%)', '101 (19%)']
['Hematological', '', '', '']
['Thrombocytopenia', '59 (11%)', '5 (1%)', '192 (37%)']
['Anemia', '15 (3%)', '1 (0%)', '150 (29%)']
['Metabolic and Nutritional', '', '', '']
['Bilirubinemia', '30 (6%)', '13 (2%)', '210 (40%)']
['Creatinine Increase', '14 (3%)', '5 (1%)', '174 (33%)']
['SGOT Increase', '17 (3%)', '3 (1%)', '122 (23%)']
['Central Nervous System', '', '', '']
['Confusion', '57 (11%)', '5 (1%)', '177 (34%)']
['Somnolence', '19 (4%)', '2 (0%)', '115 (22%)']
['Respiratory System', '', '', '']
['Dyspnea', '52 (10%)', '5 (1%)', '224 (43%)']
['Respiratory Disorders', '15 (3%)', '14 (3%)', '59 (11%)']
['Urogenital System', '', '', '']
['Oliguria', '137 (26%)', '33 (6%)', '333 (63%)']
['Anuria', '13 (1%)', '25 (5%)', '36 (7%)']
['Time of Evolution\nBefore Starting Clinical Previous\nPatient Age Gender Protocol Stage Primary Metastasis Treatment']
['CT001 34 F 36 months IV Thorax In transit and Surgery\ngland anterior\nmammary\nCT002 35 M ND IV Osseous\n(Vertebral)\nCT003 34 M 12 months IV Back Lung Surgery\nCT004 69 M 60 months IV Back Multiple Surgery, IL2\nCT005 57 M 36 months IV EII Lung Surgery\nCT006 30 M 36 months IV Thorax Subcutaneous Surgery\ninguinal left\nCT007 53 F 6 months III EII Inguinal left Surgery\nlymph nodes\nCT008 37 F 36 months IV EII Pulmonary Surgery\nCT009 24 F 8 months III Back Axillary right Surgery\nlymph nodes\nCT010 39 M 60 months IV Malar Local Enucleation\ndissemination\nCT011 68 F 30 months IV Back Liver Surgery\nCT012 57 F 14 months IV Plant left In transit Surgery, IL2\nCT013 62 M 36 months IV Scalp Lung Surgery']
['Patient', '', 'No.', '', '', 'Adverse', '', 'Elispot', 'DTH', 'Vaccination', '', 'Objective', '', '', 'Post-Therapy', '']
[None, None, 'DC/Dose', None, None, 'Reactions', None, None, None, None, None, 'Regressions', None, None, 'Disease', None]
['CT001 3-5 x 10^6 Negative + + 2nd cycle Regression Progression of\nof pulmonary\npulmonary nodules\nnodules\nCT002 3-5 x 10^6 Negative Nd Nd - - Deceased\nCT003 3-5 x 10^6 Negative + + 3rd cycle - Deceased\nCT004 3-5 x 10^6 Negative - - 1st cycle - Stable disease\nCT005 3-5 x 10^6 Fever, - - 1st cycle Regression Progression of\narthralgias of cutaneous cutaneous\nAAN and metastasis metastasis\nRF (-)\nCT006 3-5 x 10^6 Negative + + 2nd cycle - Progression\nCT007 3-5 x 10^6 Negative + - 1st cycle - Stable disease\nCT008 10 x 10^6 Negative + - Withdrawal - Deceased\n(1st dose)\nCT009 10 x 10^6 Negative + + 1st cycle - Stable disease\nCT010 10 x 10^6 Negative Nd - 1st cycle - Progression\nCT011 10 x 10^6 Negative Nd + 1st cycle - Stable disease\nCT012 10 x 10^6 Negative Nd - 2nd cycle - Progression\nCT013 10 x 10^6 Negative Nd - 1st cycle - Progression', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]

=== NCT06155006_Prot_SAP_000.pdf ===
['Category ', 'Variable  name ', 'Conceptual \ndefinition ', 'Operational \ndefinition ', 'Measuring \nscale ']
['Sociodemographic ', 'ID  Number ', 'ID  Number ', 'Personal \nidentification \nnumber  under \nwhich  you  are \nregistered  in  the \ncountry  of  origin ', 'Nominal ']
[None, 'Age ', "Duration  of  an \nindividual's \nexistence \nmeasured  in  units \nof  time. ", '\nNumber  in  years ', 'Continual \n']
[None, 'Gender  ', 'Categorizes  the ', '1.  Female ', 'Nominal ']
['Category ', 'Variable  name ', 'Conceptual \ndefinition ', 'Operational \ndefinition ', 'Measuring \nscale ']
['', '', 'individual \naccording  to  her \nbiological \ncharacteristics. ', '0.  Male \n2.  Undetermined ', '']